### ISSUE TITLE
RuntimeError: CUDA error

### ISSUE THREAD

**Issue by Jzli03** [milleniums/High-Resolution-Remote-Sensing-Semantic-Segmentation-PyTorch#8]
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
代码中错误定位在trainer.training(epoch)和writer.add_scalar('train_loss', train_loss.avg, curr_iter)请问应该如何更改

**Comment by houchenfeng** [comment]
> 

我也遇见了相同的问题，请问您解决了吗

**Comment by houchenfeng** [comment]
> 
我解决了这个问题，换用CPU之后可以发现是越界，然后找到是vis2gray.py中将一些点设置为16导致越界了。改为0就可以。

**Comment by yuxin7** [comment]
> > 
> 
> 我解决了这个问题，换用CPU之后可以发现是越界，然后找到是vis2gray.py中将一些点设置为16导致越界了。改为0就可以。

您好，我想问一下，是您重新用vis2gray将彩色mask处理成了灰度的mask？还是直接修改了vis2gray的方法。我看代码中没有调用vis2gray的方法啊。

**Comment by houchenfeng** [comment]
因为是之前为了完成大作业匆忙做的，细节记不太清了。刚刚看了一下，mask肯定是灰度的，data读入的时候就已经是单通道的数据了（mask = Image.open(mask_path).convert('L')），我应该是先用vis2gray把彩色标签转化为0-15的标签数据了，然后把处理好的标签作为训练集。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月10日(星期一) 上午10:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [milleniums/High-Resolution-Remote-Sensing-Semantic-Segmentation-PyTorch] RuntimeError: CUDA error (Issue #8)





    
我解决了这个问题，换用CPU之后可以发现是越界，然后找到是vis2gray.py中将一些点设置为16导致越界了。改为0就可以。
  
您好，我想问一下，是您重新用vis2gray将彩色mask处理成了灰度的mask？还是直接修改了vis2gray的方法。我看代码中没有调用vis2gray的方法啊。

**Comment by Wzysaber** [comment]
mask[mask >= num_class] = ignore_label
 mask[mask <= 0] = ignore_label

dataset里面加这个就可以了

**Comment by drucelee723** [comment]
谁能给一份完整的训练代码和文件阿，这个缺各种文件，config.json   权重等等

**Comment by houchenfeng** [comment]
> 谁能给一份完整的训练代码和文件阿，这个缺各种文件，config.json 权重等等

xd你缺啥了，我记得可以自己训练的啊，没缺文件吧，需要自己从头开始训练的。我的放到服务器上了，你看你缺啥文件我发你。

**Comment by drucelee723** [comment]
> > 谁能给一份完整的训练代码和文件阿，这个缺各种文件，config.json 权重等等
> 
> xd你缺啥了，我记得可以自己训练的啊，没缺文件吧，需要自己从头开始训练的。我的放到服务器上了，你看你缺啥文件我发你。

太感谢了兄弟  能加个q详聊吗，比如训练时候这个jpg他是如何生成的

**Comment by houchenfeng** [comment]
> > > 谁能给一份完整的训练代码和文件阿，这个缺各种文件，config.json 权重等等
> > 
> > 
> > xd你缺啥了，我记得可以自己训练的啊，没缺文件吧，需要自己从头开始训练的。我的放到服务器上了，你看你缺啥文件我发你。
> 
> 太感谢了兄弟 能加个q详聊吗，比如训练时候这个jpg他是如何生成的

训练里面没有生成jpg呀，loss是用tensorboardX 保存的，这几行：
https://github.com/milleniums/High-Resolution-Remote-Sensing-Semantic-Segmentation-PyTorch/blob/a68c44bbf93a2e5bc270c920f18576c76e03e1dd/train.py#L239

推理的时候就是把预测结果保存下来的：
https://github.com/milleniums/High-Resolution-Remote-Sensing-Semantic-Segmentation-PyTorch/blob/a68c44bbf93a2e5bc270c920f18576c76e03e1dd/train.py#L304

**Comment by drucelee723** [comment]
> > > > 谁能给一份完整的训练代码和文件阿，这个缺各种文件，config.json 权重等等
> > > 
> > > 
> > > xd你缺啥了，我记得可以自己训练的啊，没缺文件吧，需要自己从头开始训练的。我的放到服务器上了，你看你缺啥文件我发你。
> > 
> > 
> > 太感谢了兄弟 能加个q详聊吗，比如训练时候这个jpg他是如何生成的
> 
> 训练里面没有生成jpg呀，loss是用tensorboardX 保存的，这几行：
> 
> https://github.com/milleniums/High-Resolution-Remote-Sensing-Semantic-Segmentation-PyTorch/blob/a68c44bbf93a2e5bc270c920f18576c76e03e1dd/train.py#L239
> 
> 推理的时候就是把预测结果保存下来的：
> 
> https://github.com/milleniums/High-Resolution-Remote-Sensing-Semantic-Segmentation-PyTorch/blob/a68c44bbf93a2e5bc270c920f18576c76e03e1dd/train.py#L304

好兄弟你加一下我279595358，训练的时候读取数据这是jpg文件，我有点蒙

**Comment by hcf783** [comment]
> 

你新开一个issue说清楚就好了吧 你描述的问题我都没怎么看懂

**Comment by houchenfeng** [comment]
@drucelee723 你新开一个issue说清楚就好了吧 你描述的问题我都没怎么看懂

**Comment by drucelee723** [comment]
> @drucelee723 你新开一个issue说清楚就好了吧 你描述的问题我都没怎么看懂
好的，就是数据集应该以什么格式或者文件夹存放，

**Comment by drucelee723** [comment]
> @drucelee723 你新开一个issue说清楚就好了吧 你描述的问题我都没怎么看懂

兄弟你能上传一份您可以训练的完整代码吗

**Comment by MLS2021** [comment]
> > 谁能给一份完整的训练代码和文件阿，这个缺各种文件，config.json 权重等等
> 
> xd你缺啥了，我记得可以自己训练的啊，没缺文件吧，需要自己从头开始训练的。我的放到服务器上了，你看你缺啥文件我发你。
请问一下，config.json这个文件是什么

**Comment by hellobo2802** [comment]
> 



> > 谁能给一份完整的训练代码和文件阿，这个缺各种文件，config.json 权重等等
> 
> xd你缺啥了，我记得可以自己训练的啊，没缺文件吧，需要自己从头开始训练的。我的放到服务器上了，你看你缺啥文件我发你。

me too. 这个代码bug不断，好多地方续不上，兄弟share一下吧。
